name: "Branch Naming Rules"

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          BASE_BRANCH="${{ github.base_ref }}"
          REGEX="^(feat|fix|docs|poc|chore)\/[a-z0-9._-]+$"

          if [[ "$BRANCH_NAME" == "Dev" && "$BASE_BRANCH" == "Main" ]]; then
            echo "Dev to Main promotion branch is valid."
            exit 0
          fi
          
          if [[ ! $BRANCH_NAME =~ $REGEX ]]; then
            echo "❌ Error: Invalid branch name '$BRANCH_NAME'."
            echo "Branches must start with: feat/, fix/, docs/, poc/, or chore/"
            exit 1
          fi
          echo "✅ Branch name is valid."
