name: Mirror to Epitech

on:
  push:
    branches: [ feat/mirror-epitech-repository ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Epitech
        env:
          TOKEN: ${{ secrets.EPITECH_TOKEN }}
        run: |
          # Vérifier le nom de la branche réelle
          BRANCH_NAME=$(git branch --show-current)
          echo "Syncing branch: $BRANCH_NAME"
          
          git config --global user.name "GitHub Action Mirror"
          git config --global user.email "action@github.com"
          
          git remote add epitech https://x-access-token:$TOKEN@github.com/EpitechPromo2027/B-PRO-600-PAR-6-1-tech3internship-quentin.stoll.git
          
          # Push de la branche actuelle dynamiquement
          git push epitech $BRANCH_NAME --force